[WIP] Single Value Title and Subtitle
psu-libraries/scholarsphere-3 pull request #1007
Opened 2017-07-21 12:54 UTC by mtribone

Makes the title single value like the rights statement using Sufia 7.3 example.

Updates generic work form spec to check each parameter to make sure that they do not contain spaces.

Removes empty array from generic work field since the title is displayed as a single value string.

Adds subtitle to the model, new/edit form, show page, property to be displayed, field configurator.

Removes subtitle from attribute rows, adds subtitle to the show page under the title, and creates new subtitle partial.

Moves the subtitle back to the show fields and fixes the catalog controller and field configurator tests for the addition of subtitle.

Reworks primary terms method to include subtitle unerneath title in the required metadata section.

Adds headings to sufia.en.yml file for the new/edit work form.

2017-07-21 14:30 UTC, mtribone commented
<img width="1042" alt="screen shot 2017-07-21 at 10 29 02 am" src="https://user-images.githubusercontent.com/4163828/28467948-83f0f13e-6dff-11e7-8f9e-0cbd2f3b3349.png">

2017-07-21 14:30 UTC, mtribone commented
<img width="1031" alt="screen shot 2017-07-21 at 10 28 42 am" src="https://user-images.githubusercontent.com/4163828/28467977-97ac32c4-6dff-11e7-9e52-295a810eaf43.png">

2017-07-21 14:31 UTC, mtribone commented
<img width="1050" alt="screen shot 2017-07-21 at 10 30 41 am" src="https://user-images.githubusercontent.com/4163828/28468007-b2c42ba2-6dff-11e7-9338-94a63c0501d8.png">

2017-07-21 15:18 UTC, awead requested changes

2017-07-21 15:18 UTC, awead commented on app/services/field_configurator.rb
> +             subtitle: FieldConfig.new(label: "Subtitle", index_solr_type: :stored_searchable))
I think `stored_searchable` is the default and can be removed here.

2017-07-21 15:18 UTC, awead commented on app/views/curation_concerns/base/_work_subtitle.erb
> +<% if @presenter.subtitle.present? %>
Because you've passed in `@presenter` as the local variable `presenter` (see below) you ought to use the local one instead.

2017-07-21 15:19 UTC, awead commented on app/views/curation_concerns/base/_work_subtitle.erb
> +<% if @presenter.subtitle.present? %>
I meant "see below" as in this: https://github.com/psu-stewardship/scholarsphere/pull/1007/files#diff-e8df3522061376ee39e0afe98507f5e0R21

2017-07-21 15:30 UTC, mtribone commented on app/services/field_configurator.rb
> +             subtitle: FieldConfig.new(label: "Subtitle", index_solr_type: :stored_searchable))
Then I can probably remove `label` too.

2017-07-21 16:15 UTC, awead commented on app/services/field_configurator.rb
> +             subtitle: FieldConfig.new(label: "Subtitle", index_solr_type: :stored_searchable))
oh yeah! that too...

2017-07-24 12:36 UTC, awead approved these changes

2017-07-24 12:36 UTC, merged