Work Show Metadata List
psu-libraries/scholarsphere-3 pull request #1035
Opened 2017-09-15 14:06 UTC by mtribone

Reorders the metadata to match the work form, moves other attributes out of the metadata partial and into the attribute rows partial, and makes adjustment to the spacing of the definition terms.

2017-09-15 14:07 UTC, mtribone commented
Large screen flavor

![screen shot 2017-09-15 at 10 03 35 am](https://user-images.githubusercontent.com/4163828/30486148-9dceacac-99fd-11e7-8549-1e51766a89b6.png)

2017-09-15 14:07 UTC, mtribone commented
Small screen flavor

![screen shot 2017-09-15 at 10 05 43 am](https://user-images.githubusercontent.com/4163828/30486180-af2b0c2a-99fd-11e7-99b4-b263826a7f1b.png)

2017-09-18 11:37 UTC, carolyncole requested changes
@mtribone My only comment is we should likely not be displaying AdminSet to the user.

2017-09-18 11:37 UTC, cam156 commented on app/views/curation_concerns/base/_attribute_rows.html.erb
> +<%= presenter.attribute_to_html(:admin_set, render_as: :faceted) %>
I wonder if we should leave admin_set out for the moment.  I believe currently this will always be the default adminset

2017-09-18 17:09 UTC, carolyncole approved these changes

2017-09-18 17:09 UTC, merged