Refactor UserStatsImporter
psu-libraries/scholarsphere-3 pull request #1036
Opened 2017-09-15 19:08 UTC by awead

From our Friday refactoring session, we extracted the various tally
methods into a new class and removed the inheritance from
Sufia::UserStatImporter.

2017-09-18 11:41 UTC, carolyncole requested changes
@awead At some point we will need to add tests for the new class.  Did you want to add those now or should we add a ticket?  It should be a matter of taking some of the test from UserStats and putting them against UserStatisticReport.

2017-09-18 11:41 UTC, cam156 commented on app/services/user_stats_importer.rb
> +    def create_or_update_user_stats(stats, user)
Should we add a comment that this code was copied from Sufia::UserStat?

2017-10-24 13:24 UTC, cam156 commented
@awead I'm not certain if this is an accurate code coverage drop.  Are you happy with the coverage on this PR?

2017-10-24 13:36 UTC, awead commented
@cam156 yeah, I wasn't either. I'm happy if you are!

2017-10-26 12:04 UTC, cam156 commented
@awead if I am reading code coverage right it looks like import is not being tested
https://coveralls.io/builds/13847428/source?filename=app%2Fservices%2Fuser_stats_importer.rb#L12

2017-10-27 15:13 UTC, merged