Allow ordering of alias objects in place of persons, ref #991, #949
psu-libraries/scholarsphere-3 pull request #1039
Opened 2017-09-19 15:54 UTC by awead

This makes two main changes: 1) Creates an Alias resource that stands between a work and its creator; and 2) orders aliases using a membership predicate.

Previously, a work would contain one or more Person objects as creators. In order to allow for different names for the same canonical person, an Alias class holds a display name and a reference to a single canonical user. The `AliasManagementService` is responsible for finding or creating persons and aliases to attach to new or existing works.

Forms for works can now accept either new creators or edit existing ones. When new creators are added, both aliases and persons are created as needed, via the `AliasManagementService`, or if display names are changed, new aliases are added to the existing person, also via the `AliasManagementService`.

2017-09-19 16:36 UTC, carolyncole requested changes
Overall looks very good.  Added a few inline comments.  My big overall question is it seems like you can not create a Person/Alias by filling in the user Given and Surname.  The goal is not to need to parse a string every time, but allow the user to give us that information in parts.  I can not tell, but it seems like this PR is removing that ability.

2017-09-19 16:36 UTC, cam156 commented on app/assets/javascripts/scholarsphere/creator/creator.js
> +  lastName: '', displayName: '',
A Style comment.  Since every item is on it's own line it would be better to add the displayName on a separate line.

2017-09-19 16:36 UTC, cam156 commented on app/services/generic_work_to_share_json_service.rb
> +        creator_name = [creator.person.sur_name, creator.person.given_name].compact.join(', ')
Should this really just be display_name?

2017-09-19 16:36 UTC, cam156 commented on spec/features/dashboard/dashboard_collections_spec.rb
> +    expect(page).to have_content(collection.creator.first.display_name)
Could this just be `expect(page).to have_content(creator.display_name)`

2017-09-19 16:36 UTC, cam156 commented on spec/features/dashboard/dashboard_works_spec.rb
> -           creators: [create(:creator)],
@awead I think the reason for using a different creator was to make sure the query was filtering.  When you put in the same creator we have no idea if we are getting all or just the records we want.

2017-09-19 16:36 UTC, cam156 commented on spec/forms/generic_work_form_spec.rb
> +      its(:display_name) { is_expected.to eq('Test A User') }
Doesn't the form still show the given_name and sur_name?

2017-09-19 16:36 UTC, cam156 commented on spec/models/generic_work_spec.rb
> +        work.creators.build(display_name: 'Frodo')
Can we build with a first and last name?

2017-09-19 16:47 UTC, mtribone commented on app/assets/javascripts/scholarsphere/creator/creator.js
> +  lastName: '', displayName: '',
Certainly. My editor kept indenting it 2 spaces and was annoying me, so I just kept it on the same line.  :-)

2017-09-19 17:23 UTC, awead commented on app/services/generic_work_to_share_json_service.rb
> +        creator_name = [creator.person.sur_name, creator.person.given_name].compact.join(', ')
@cam156 yes, I thought the same too. I was thinking that the we ought to link the SHARE resource off the canonical name of the person, as opposed to the alias, otherwise we might have different users in SHARE that are the same person.

2017-09-19 17:30 UTC, awead commented
@cam156 We could make `display_name` optional in the form, which would mean that if it is blank, `AliasManagementService` returns the first alias it finds for the person. `given_name` and `sur_name` would have to be required because that's what we use to find the person--actually, this is what the search form is doing for us, so no problem there.

If a display name is provided, then it would create a new alias if that display name did not already exist.

Is this what you were thinking of?

2017-09-19 17:34 UTC, awead commented on spec/models/generic_work_spec.rb
> +        work.creators.build(display_name: 'Frodo')
@cam156 no, because `build` is expecting an `Alias` which doesn't have those attributes, but we could use `person`, I think, like: `work.creators.build(display_name: 'Frodo', person: Person.new(given_name: 'Frodo', sur_name: 'Baggins'))` but the model doesn't care about the person at this point. The presence or absence of a person is enforced at the `creators=` method via `AliasManagementService`. But, there's no harm in doing the above... it makes it more complete, I guess.

2017-09-19 17:40 UTC, awead commented on spec/forms/generic_work_form_spec.rb
> +      its(:display_name) { is_expected.to eq('Test A User') }
It shows all three: display, given, and sur. Is that what's supposed to happen?

2017-09-19 17:58 UTC, cam156 commented on app/services/generic_work_to_share_json_service.rb
> +        creator_name = [creator.person.sur_name, creator.person.given_name].compact.join(', ')
@awead makes sense. There is likely more work in the share module so let's just leave it alone for now.

2017-09-19 17:59 UTC, cam156 commented on spec/forms/generic_work_form_spec.rb
> +      its(:display_name) { is_expected.to eq('Test A User') }
@awead I was commenting on the fact that the test only tests display name now.  Seemed like the form could no longer have the other two

2017-09-19 18:01 UTC, cam156 commented
@awead I just got a bit worried becuase all the tests were just checking display name.  I think display name being required is ok, as long as we default it to `"#{surname}, #{given_name}"`

2017-09-19 18:02 UTC, cam156 commented
@awead that said the defaulting does not need to be part of this PR.  Just something we should do to help out the users.

2017-09-19 19:14 UTC, awead commented on spec/features/dashboard/dashboard_works_spec.rb
> -           creators: [create(:creator)],
@cam56 I put in a different creator name for `work1` which will differ from the creator name used in the facet count check.

2017-09-19 19:14 UTC, awead commented on spec/forms/generic_work_form_spec.rb
> +      its(:display_name) { is_expected.to eq('Test A User') }
@cam156 I've expanded the tests to include checks for given and surnames.

2017-09-19 19:19 UTC, awead commented
@cam156 presently, `display_name` is defaulting to whatever the display name for the record in `User` is, which is what's just coming out of LDAP. For me, this is _ADAM GARNER WEAD_, in all caps and not, for example, _Wead, Adam Garner_. Do we want to change that? The other issue with this is what if a user prefers a particular display name? For example, I always want to be _Dr. Adam Wead_ and I'd have to change that each time I deposit unless I set a preferred alias or have the form look for whatever my current alias is... That would be a good follow-up PR.

2017-09-20 11:50 UTC, carolyncole approved these changes

2017-09-20 11:50 UTC, merged