Additional properties to Person, ref #961
psu-libraries/scholarsphere-3 pull request #1061
Opened 2017-10-26 15:50 UTC by awead

Adds email, PSU id, and Orcid id to the Person model so we can store
these values when users want to add them.

2017-10-27 15:27 UTC, carolyncole requested changes

2017-10-27 15:27 UTC, cam156 commented on app/controllers/persons_controller.rb
> +      aliases.each do |aliaz|
@awead how about agent_alias?  We are never going to know to search for aliaz if we are looking at the code.

2017-10-27 15:27 UTC, cam156 commented on app/controllers/persons_controller.rb
> +          "id:#{aliaz['name_ssim'].first}",
@awead how is the name the ID?  That seems strange

2017-10-27 15:27 UTC, cam156 commented on app/forms/creator_form.rb
> +    return unless read_only_name?
I'm wondering based on the fact that we are using read_only_name? for things that are not related to name if we should change that to just read_only?

2017-10-27 15:27 UTC, cam156 commented on spec/factories/persons.rb
> +    orcid_id   '00123445'
I wonder if we care about validating the orcid.

2017-10-27 15:31 UTC, awead commented on app/controllers/persons_controller.rb
> +          "id:#{aliaz['name_ssim'].first}",
@cam156 This one got me too. It's generated by ActiveFedora's solr name stuff. Specifically, when you define the relationship using the `name` predicate here:

https://github.com/psu-stewardship/scholarsphere/blob/user-object-961/app/models/alias.rb#L6

I would have expected `person_ssim`, but I guess not.

2017-10-27 15:33 UTC, awead commented on spec/factories/persons.rb
> +    orcid_id   '00123445'
@cam156 dunno. I imagine we should. We put that in another ticket and validate by some concrete means, like length, etc., and then look at a future option that could query the orchid service directly, like an autocomplete or just a call back that's done at some point.

2017-10-27 17:05 UTC, cam156 commented on .rubocop_todo.yml
> -require: rubocop-rspec
@awead did you intend to remove rubocop-rspec?

2017-10-27 18:59 UTC, awead commented on .rubocop_todo.yml
> -require: rubocop-rspec
hmm. no. I think auto-gen did that.

2017-10-30 15:01 UTC, awead commented on .rubocop_todo.yml
> -require: rubocop-rspec
@cam156 `--auto-gen-config` seems to have done that. I'm not sure why it's showing up now, but the require is in `.rubocop_yml` so it doesn't need to be in the todo file.

2017-10-30 15:03 UTC, awead commented
@cam156 I took a look at the coveralls changes, and the missing coverage doesn't seem to be related to any of the changes in this PR.

2017-10-30 15:21 UTC, awead commented
@cam156 oohhh-kay.... now it says coverage increased. I rebased it, so maybe that was it.

2017-10-31 13:00 UTC, merged