Use WorkShowPresenter for recent and featured works, ref #998
psu-libraries/scholarsphere-3 pull request #1064
Opened 2017-10-30 17:37 UTC by awead

@cam156 @mtribone this alters the views of recent and featured works to make them exactly like the show view. This way, we're using the same renderer code that we use to translate facets. The original problem was identified in #998, but we discovered is also was present in recent and featured works because they weren't using the same renderer process.

The question is, do we need to tweak the layout or display:
![featured](https://user-images.githubusercontent.com/312085/32186017-44d0ea28-bd77-11e7-807a-fa2ef47bfee4.png)
![recent](https://user-images.githubusercontent.com/312085/32186020-486560f6-bd77-11e7-8ca0-8cd2aff2840c.png)

2017-10-30 17:51 UTC, mtribone commented
@awead I say that if it visually matches what is currently in production, we are good to go. Otherwise I could tweak that layout all week!

2017-10-30 18:40 UTC, awead commented
@mtribone it doesn't. Here's what's currently in production:
![current](https://user-images.githubusercontent.com/312085/32189118-2ee47334-bd80-11e7-952e-00f512bb2e0c.png)
Note the bold-face field names.

2017-10-30 18:47 UTC, mtribone commented
They just need some `class="sr-only"` on them.

2017-10-30 18:48 UTC, mtribone commented
![screen shot 2017-10-30 at 2 48 06 pm](https://user-images.githubusercontent.com/4163828/32189546-670d482a-bd81-11e7-8ac4-bb48082e4440.png)

2017-10-30 18:55 UTC, awead commented
@mtribone ok, but my point was that we could make the same as the show view, which displays those field names instead of hiding them visually. Otherwise, we'd need to create separate renderers for each fields displayed.

2017-10-30 19:12 UTC, mtribone commented
@awead okay. so if you'd like to just use the same partial and have them be the same, go for it. Does creator show the bold term or just the other metadata?

2017-10-30 19:31 UTC, awead commented
@mtribone it's the depositor, not creator, so we'd probably have to make a new renderer for that. I'm open to suggestions!

2017-10-31 12:36 UTC, olendorf commented
looks fine to me

2017-10-31 12:51 UTC, mtribone commented
@awead @olendorf I'm good with this for now.

2017-10-31 12:59 UTC, carolyncole requested changes

2017-10-31 12:59 UTC, cam156 commented on spec/features/featured_work_spec.rb
> +      expect(page).to have_content(file1.title[0])
@awead curious why the second check of title

2017-10-31 13:02 UTC, awead commented on spec/features/featured_work_spec.rb
> +      expect(page).to have_content(file1.title[0])
@cam156 line 24 clicks on the facet link and we want to make sure it shows the work. Previously, this was not working because the facet wasn't being correctly translated.

2017-11-01 19:09 UTC, merged