Single Title and Subtitle for Collections
psu-libraries/scholarsphere-3 pull request #1072
Opened 2017-11-13 15:21 UTC by mtribone

Adds subtitle term to collection form, redefines title method to grab first title, addresses multiple titles, adds subtitle to the primary terms on the form, and adds the subtitle as a new property in the model.

Adds the subtitle field to the collection show page, adds the collection subtitle partial, delegates subtitle to solr in the collection presenter.

Updates create and edit spec test to test for subtitle.

Fixes style error in test for the collection presenter and adds subtitle to the collection form test.

2017-11-13 15:22 UTC, mtribone commented
![screen shot 2017-11-13 at 10 22 07 am](https://user-images.githubusercontent.com/4163828/32733170-931b8b44-c85c-11e7-9a0e-bd5bf4f4f894.png)

2017-11-13 18:51 UTC, carolyncole requested changes

2017-11-13 18:51 UTC, cam156 commented on app/forms/collection_form.rb
> +    if [:title].include? field.to_sym
`if field.to_sym == :title` would be an easier way of saying this.

2017-11-13 18:51 UTC, cam156 commented on db/schema.rb
> -  add_foreign_key "mailboxer_notifications", "mailboxer_conversations", column: "conversation_id", name: "notifications_on_conversation_id_development"
This file should be excluded

2017-11-13 18:51 UTC, cam156 commented on spec/features/collection/edit_spec.rb
> +      fill_in 'Subtitle', with: updated_subtitle
There are two check below after the Update button is clicked that I would expect to also see for the subtitle.  Make sure the original subtitle is not present.   Make sure the new subtitle is present.

2017-11-13 19:03 UTC, mtribone commented on db/schema.rb
> -  add_foreign_key "mailboxer_notifications", "mailboxer_conversations", column: "conversation_id", name: "notifications_on_conversation_id_development"
oopsies. I forgot to check it out again after I migrated the database.

2017-11-14 14:42 UTC, carolyncole requested changes
@mtribone everything looks good except for the schema file.

2017-11-14 15:29 UTC, merged