Enable ordered creators with custom predicate, ref #949, #1049
psu-libraries/scholarsphere-3 pull request #1096
Opened 2017-11-16 18:42 UTC by awead

Implementing an ordered aggregation for creators was not preserving
their order.

The ordered aggregation is removed in favor of a simpler property and a
second custom predicate that maintains the order of creators as a
delimited string of ids.

2017-11-16 18:53 UTC, carolyncole requested changes

2017-11-16 18:53 UTC, cam156 commented on app/models/concerns/has_creators.rb
> +      super(agent_records.map(&:uri))
@awead is the map to uri change needed?

2017-11-16 18:53 UTC, cam156 commented on app/models/concerns/has_creators.rb
> +      creators.map(&:id)
Should this use the ordered list?

2017-11-16 18:53 UTC, cam156 commented on app/models/concerns/has_creators.rb
> +    def ordered_creator_ids
@awead is there a reason we would want the unordered creators?  I would think we would always want the order.

2017-11-16 18:53 UTC, cam156 commented on spec/support/helpers/solr_objects.rb
> +  conn.add(collection.to_solr.merge!('creator_sim' => creator))
@awead I realize this is less lines of code, but is it really more readable?

2017-11-16 18:57 UTC, awead commented on app/models/concerns/has_creators.rb
> +      super(agent_records.map(&:uri))
Yes, it doesn't work with Alias objects, you have to use their uris.

2017-11-16 19:02 UTC, awead commented on app/models/concerns/has_creators.rb
> +    def ordered_creator_ids
`creator_ids` could be a bit faster because it's not pulling the `creator_list` predicate and sorting through each one. That may be extra hits to Fedora. It also mimics the `ordered_members` vs. `members` distinction.

2017-11-16 19:08 UTC, awead commented on spec/support/helpers/solr_objects.rb
> +  conn.add(collection.to_solr.merge!('creator_sim' => creator))
It's less overall lines of code to read, and one less variable to have to keep in your head.

2017-11-16 19:08 UTC, awead commented on app/models/concerns/has_creators.rb
> +      creators.map(&:id)
It's being used in `SolrListMigrator`

2017-11-16 19:49 UTC, cam156 commented on spec/support/helpers/solr_objects.rb
> +  conn.add(collection.to_solr.merge!('creator_sim' => creator))
@awead I would suggest that reading the one line I have to parse it to know what it does, where the multiple lines makes it obvious that er get the solr, change the creator and then send the hash to solr.

2017-11-16 19:50 UTC, cam156 commented on spec/support/helpers/solr_objects.rb
> +  conn.add(collection.to_solr.merge!('creator_sim' => creator))
@awead this is not boring ruby.  It is fancy ruby I might hesitate to touch later.  Not sure this change is at all related to this PR.

2017-11-16 22:00 UTC, awead commented on spec/support/helpers/solr_objects.rb
> +  conn.add(collection.to_solr.merge!('creator_sim' => creator))
@cam156 I pushed up a change. I had a lot of problems with these helpers because it wasn't clear that they were trying to mimic the old form of creators. I added some comments to clear that up, and hopefully the updated method makes that more clear. I spent some time trying to  make a factory that would create a collection or work with the complete form of "old" creators, but that wasn't working out. So I've opted for an extracted method to help clear things up.

2017-11-17 16:33 UTC, carolyncole reviewed
@awead just to be certain I am reading the PR correctly.  When you get the ids you always get them in order, but when you get the object you can get them either in order or in random order?  If that is correct that does not match with how the system currently works.  Creators are expected to be ordered when getting or setting them.

2017-11-17 16:33 UTC, carolyncole commented on app/forms/batch_edit_form.rb
> +        combined_creators.push(*work.creators)
Should this be ordered?

2017-11-17 16:33 UTC, carolyncole commented on app/models/batch_edit_item.rb
> +    batch.map(&:creators).map(&:to_a).flatten
Should this be ordered?

2017-11-17 16:33 UTC, carolyncole commented on app/models/concerns/has_creators.rb
> +      creators.map(&:id)
@awead that should then use ordered list since we want to preserve order I would think when we migrate.

2017-11-17 16:33 UTC, carolyncole commented on app/models/concerns/has_creators.rb
> +    def ordered_creator_ids
Ok then we need to change all references to creator_ids and creators ordered creators.

2017-11-17 16:51 UTC, awead commented
@cam156 the order of creators are set in `creators=` via the `creator_list` predicate. If we want `creators` to return the ordered set, we'd need to override `creators` which is meta-programmed method and could have unintended consequences. However, we're overriding `creators=` which is also meta-programmed, so we're only making it slightly worse.

2017-11-17 17:00 UTC, cam156 commented
@awead to be certain we are not going to lose our ordering some how it would make sense to override creators.
I could see someone doing this
```
local_creators = object.creators
...
local_creators << new_creator
object.creators = creators
```
That might loose the original ordering.  I also wonder would
`object.creators << new_creator loose the order?` or `object.creators +=[new_creator]`

Yes I may be being a bit paranoid, but this is a large change to be introducing so late.  Maybe we need a full regression test if you really want to change the behavior.

2017-11-17 17:17 UTC, awead commented
@cam156 I don't think we can rely on `<<` and `+=` might work, but I would only be certain of using `=` and nothing else. At this point, the only interface to updating the creators should be `creators=`. I can override `creators` and see what happens.

2017-11-17 23:30 UTC, merged