Aligns Fieldset Permission Tab with Work Permission Tab
psu-libraries/scholarsphere-3 pull request #1141
Opened 2018-01-10 14:24 UTC by mtribone

Refactors the permissions tab for fiieldsets to more closely resemble the permissions, visibility, sharing section of the work form. Addresses accessibility concerns for the ticket, but not overall for the page. Additional tickets need to be created for the bootlint and WAVE errors.

2018-01-10 14:25 UTC, mtribone commented
Old Version

![screen shot 2018-01-10 at 9 24 28 am](https://user-images.githubusercontent.com/4163828/34777376-2a7a1f88-f5e8-11e7-99cf-fd5bedc3939c.png)

2018-01-10 14:25 UTC, mtribone commented
New Version

![screen shot 2018-01-10 at 9 22 30 am](https://user-images.githubusercontent.com/4163828/34777389-366fb938-f5e8-11e7-96c9-4724ea24c92e.png)

2018-01-10 16:32 UTC, awead commented
@mtribone Looks good to me. I'm not really sure what tests we could write for this, unless you want to throw in some checks for headings and text in one of the feature tests.

2018-01-10 18:05 UTC, mtribone commented
@awead Yeah I could write some tests to make sure certain things for accessibility aren't removed.

2018-01-10 19:51 UTC, mtribone commented
@awead I'll write a test to make sure that the structure of the document outline for permissions is a certain way within the structure of the overall page.

2018-01-10 21:24 UTC, awead commented
@mtribone the spec test file isn't named correctly. It should be `spec/features/file_set/permissions_sharing_spec.rb`

2018-01-11 12:25 UTC, cam156 commented
@mtribone I believe the "Share Work" is inappropriate verbiage at the FileSet level.  I have a similar issue with reusing that partial for the Collection, but have been tackling mystery errors instead.  I was thinking about passing in a local for the Word and defaulting it to "Work"

2018-01-11 12:31 UTC, carolyncole requested changes
I think instead of copying code we should try to reuse partials in the views.  This might be an opportunity to pair.

2018-01-11 12:31 UTC, cam156 commented on app/views/curation_concerns/file_sets/_permission_form.html.erb
> +    <h3>Share work with other users</h3>
@mtribone THis should be Share FileSet.  I made a comment on the entire PR.  Since this is the same as the Work except for the word "Work" you could possibly just reuse the partial.
```
  <div id="share" class="collection_form_sharing" data-param-key="collection">
    <%= render 'curation_concerns/base/form_share', f: f, object_type: 'file' %>
  </div>
```
The partial would need to change to use the object_type in place of the hard coded 'Share work'

2018-01-12 14:10 UTC, carolyncole requested changes

2018-01-12 14:10 UTC, cam156 commented on app/views/curation_concerns/base/_form_share.html.erb
> +  <% if f.object_name == 'generic_work' %>
```
<% 
object_name = 
   if f.object_name == 'generic_work'
      work
  else
      file
  end
%>
```

```
<h2> Share <%= object_name %> </h2>

2018-01-15 13:42 UTC, carolyncole approved these changes

2018-01-15 13:42 UTC, cam156 commented on app/views/curation_concerns/base/_form_share.html.erb
> +<% object_name = I18n.t("scholarsphere.model_display_name.#{f.object_name}") %>
👍

2018-01-15 13:42 UTC, merged