Copies Value of ORCID ID from Profile to Agent ORCR ID
psu-libraries/scholarsphere-3 pull request #1148
Opened 2018-01-19 14:48 UTC by mtribone

Creates new method in the user controller and checks to see if an orcid from User is present and the User login equals the Agent PSU ID and assigns the value from orcid to orcid_id.

Sets a variable for agent, makes sure that an orcid and agent is present and assigns the orcid from user to agent. Saves agent. Adds permitted parameters.

Tests that there is a redirect after profile update, reloads the user ORCID and makes sure that it is present and equals the correct value. Assigns it to the Agent ORCID ID and saves, then checks to make sure that the value is correct.

Fixes #1101

2018-01-19 15:15 UTC, mtribone commented
@awead Please scrutinize this PR as I am doing things with ORCID IDs and Agent.

2018-01-19 16:16 UTC, awead requested changes
The spec test needs a little work, but otherwise this is a fine approach.

2018-01-19 16:16 UTC, awead commented on app/controllers/users_controller.rb
> +  end
would a `after_update` hook be better here instead of overriding `update`?

2018-01-19 16:16 UTC, awead commented on spec/controllers/users_controller_spec.rb
> +      agent.save
The above two lines need to be removed. The assertion you're testing on line 22 is being explicitly set here, so the test really isn't doing anything. I think you want to just assert that the agent's orcid id is set correctly, which the controller should be doing for you. Changing line 7 to `let!(:agent)` will create the agent before the test is run, and then the controller should be able to find it when it runs. You could also add another assertion above line 14, before the controller call, that verifies `agent.orcid_id` is nil.

2018-01-19 16:18 UTC, cam156 commented
@mtribone this is one part of #1101.  It hooks into the edit and copies. We would still need "Need a way to copy existing user ORCIDs to agents".  Could you change the comment to refs?

2018-01-19 18:10 UTC, mtribone commented on app/controllers/users_controller.rb
> +  end
So in the User model, instead of overriding update, I can just simply state `after_update copy_orcid_id` ?

2018-01-19 18:26 UTC, awead commented on app/controllers/users_controller.rb
> +  end
@mtribone yep!

2018-01-22 20:05 UTC, awead approved these changes

2018-01-23 13:32 UTC, merged