Updating local LDAP tests, ref #1163
psu-libraries/scholarsphere-3 pull request #1165
Opened 2018-01-25 15:05 UTC by awead

The responses from our LDAP server have changed slightly, making the
NameDisambiguation test fail.

We've updated the tests to correspond with the new output from LDAP. One
test is marked pending because the user no longer exists.

2018-01-25 19:55 UTC, carolyncole requested changes
Looks good except for the pending.  Added a suggestion for removing the pending.

2018-01-25 19:55 UTC, cam156 commented on spec/services/name_disabiguation_service_spec.rb
> +      pending 'User is no longer in LDAP'
The test was really testing removing the * that Sue Paterno had next to her name.  We could just use one of us with a star

2018-01-26 15:04 UTC, awead commented
@cam156 amended.

2018-01-26 15:27 UTC, carolyncole approved these changes

2018-01-26 15:27 UTC, merged