Adding in translation for Work show page for identifiers
psu-libraries/scholarsphere-3 pull request #1188
Opened 2018-03-14 16:45 UTC by cam156

refs #1176 

Original view:
![screen shot 2018-03-14 at 12 44 44 pm](https://user-images.githubusercontent.com/1599081/37416953-86ee6e26-2785-11e8-88ba-dde6f66a1590.png)

New view:
![screen shot 2018-03-14 at 12 43 51 pm](https://user-images.githubusercontent.com/1599081/37416915-6aab25a6-2785-11e8-872b-65a325a22646.png)

2018-03-14 18:46 UTC, awead requested changes

2018-03-14 18:46 UTC, awead commented on app/renderers/translated_doi_attribute_renderer.rb
> +# "cleaned" using the SolrDocumentGroomer.
These comments don't seem to apply to this class.

2018-03-14 18:46 UTC, awead commented on app/views/curation_concerns/base/_attribute_rows.html.erb
> +<%= presenter.attribute_to_html(:identifier, render_as: :translated_doi, search_field: 'identifier_tesim') %>
If you're using the `show_fields/_identifier.html.erb` partial below, I'm wondering if this has any effect?

2018-03-15 11:33 UTC, cam156 commented on app/views/curation_concerns/base/_attribute_rows.html.erb
> +<%= presenter.attribute_to_html(:identifier, render_as: :translated_doi, search_field: 'identifier_tesim') %>
@awead this is for the work.  The other if for the collection

2018-03-15 11:38 UTC, cam156 commented
@awead I updated the comments.

2018-03-15 12:39 UTC, awead approved these changes

2018-03-15 18:27 UTC, merged