Adding zip capabilities for downloading an entire work
psu-libraries/scholarsphere-3 pull request #1194
Opened 2018-03-19 18:00 UTC by cam156

Adds rubyzip gem
Add WorkZipService
Modifies download controller to download the work as a zip
Adds view changes to include downloading the work on the work show page

refs #625

2018-03-19 19:07 UTC, awead requested changes

2018-03-19 19:07 UTC, awead commented on app/controllers/downloads_controller.rb
> +        super
@cam156 what about a guard clause here? Or do you anticipate more cases?

2018-03-19 19:07 UTC, awead commented on app/services/work_zip_service.rb
> +#
yay docs!

2018-03-19 19:07 UTC, awead commented on spec/controllers/downloads_controller_spec.rb
>        it 'redirects' do
Are you still testing a redirect here, or the zip download?

2018-03-19 19:07 UTC, awead commented on app/services/work_zip_service.rb
> +        if file_set.original_file.present? && (ability.can? :read, file_set.id)
You could combine the above two lines into a `select` and remove an indentation level; optional, if you think this is more readable.

2018-03-20 14:08 UTC, awead approved these changes

2018-03-20 16:54 UTC, cam156 commented
@awead this PR is all fixed up.  Coveralls is angry becuase I only added unit tests for the zip service.

2018-03-20 17:05 UTC, merged