Adding rake task to dump and truncate search table
psu-libraries/scholarsphere-3 pull request #1201
Opened 2018-03-23 16:30 UTC by cam156

refs #1025

Additionally adds cronjob to run it yearly

This has not been tested on a server since QA was unavailable for testing, but I want to put the code out for review.

2018-03-23 20:33 UTC, awead reviewed
Just had one question about the exit status.

2018-03-23 20:33 UTC, awead commented on config/cronjobs/dump_and_truncate_searches.bash
> +exit 0;
Should the script always exit successfully even if the rake command does not?

2018-04-03 15:13 UTC, cam156 commented
@awead This is updated

2018-04-03 17:17 UTC, awead requested changes

2018-04-03 17:17 UTC, awead commented on config/cronjobs/dump_and_truncate_searches.bash
> +  SUBJECT="`hostname` trncate search"
@cam156 shouldn't this be `truncate`?

2018-04-03 17:17 UTC, awead commented on config/cronjobs/dump_and_truncate_searches.bash
> +exit exit_status;
@cam156 I'm not seeing where `exit_status` is defined. Is this a bash built-in function?

2018-04-03 18:32 UTC, cam156 commented on config/cronjobs/dump_and_truncate_searches.bash
> +exit exit_status;
No good call I decided to email vs exit with a code, since this only happens yearly.  No one is going to remember to check the logs.  That should just be zero.

2018-04-03 19:46 UTC, awead approved these changes

2018-04-04 14:41 UTC, merged