Refactor Stylesheet Syntax - SCSS Lint
psu-libraries/scholarsphere-3 pull request #1209
Opened 2018-03-28 12:21 UTC by mtribone

Breaks hex colors into variables, switches to Sass comments, and adds some skip declarations for the linter when you have to override very specific CSS from other gems.

Reworks the application.css file to load files in a specific order so that the variables load first and then the rest of the files.

2018-03-28 12:36 UTC, awead requested changes
Make sure to re-enable the linters you've disabled.

2018-03-28 12:36 UTC, awead commented on app/assets/stylesheets/scholarsphere/fixedsticky.scss
> +  // scss-lint:disable VendorPrefix
Be sure to add `// scss-lint:reenable VendorPrefix` when you're done with the block.

2018-03-28 12:36 UTC, awead commented on app/assets/stylesheets/scholarsphere/fixedsticky.scss
> +  // scss-lint:disable ImportantRule
Reenable where needed.

2018-03-28 18:01 UTC, awead requested changes

2018-03-28 18:01 UTC, awead commented on app/assets/stylesheets/scholarsphere/blacklight_gallery.scss
> +// scss-lint:disable SelectorDepth, IdSelector
@mtribone is it better to disable this for the entire file via a yml config?

2018-03-28 18:01 UTC, awead commented on app/assets/stylesheets/scholarsphere/fixedsticky.scss
> +    // scss-lint:disable VendorPrefix
needs to be re-enabled

2018-03-28 18:01 UTC, awead commented on app/assets/stylesheets/scholarsphere/fixedsticky.scss
> +    // scss-lint:disable ImportantRule
reenable

2018-03-28 18:01 UTC, awead commented on app/assets/stylesheets/scholarsphere/header.scss
> +  // scss-lint:disable IdSelector
reenable.

2018-03-28 18:01 UTC, awead commented on app/assets/stylesheets/scholarsphere/header.scss
> +  // scss-lint:disable IdSelector, SelectorDepth
reenable SelectorDepth. Maybe just disable IdSelector for the whole file in a yaml config?

2018-03-28 18:01 UTC, awead commented on app/assets/stylesheets/scholarsphere/home_page.scss
> +// scss-lint:disable ImportantRule, SelectorFormat
ImportantRule seems to be disabled a lot. What about just disabling it system-wide?

2018-03-28 18:01 UTC, awead commented on app/assets/stylesheets/scholarsphere/home_page.scss
> +// scss-lint:disable IdSelector
IdSelector is disabled a lot too. Is it worth disabling that system-wide too?

2018-03-28 18:52 UTC, mtribone commented on app/assets/stylesheets/scholarsphere/home_page.scss
> +// scss-lint:disable ImportantRule, SelectorFormat
I think it would be good to keep it enabled system-wide and just cover the exceptions

2018-03-28 18:53 UTC, mtribone commented on app/assets/stylesheets/scholarsphere/home_page.scss
> +// scss-lint:disable IdSelector
I'd like to keep it just for the exceptions

2018-03-28 18:54 UTC, mtribone commented on app/assets/stylesheets/scholarsphere/fixedsticky.scss
> +    // scss-lint:disable VendorPrefix
ah. crud.

2018-03-29 17:33 UTC, awead approved these changes

2018-03-29 18:34 UTC, merged