APPINT-622: Added newrelic code for updated deployment tags
psu-libraries/scholarsphere-3 pull request #1256
Opened 2018-05-25 21:28 UTC by informaticianme

This PR adds code which allows the newrelic gem to automatically tag deployments within the newrelic rpm portal.

2018-05-29 12:19 UTC, cam156 commented
@informaticianme have you tested this out on QA?

2018-06-01 16:30 UTC, awead requested changes

2018-06-01 16:30 UTC, awead commented on config/deploy.rb
> +after 'deploy:updated', 'newrelic:notice_deployment'
@informaticianme I think this can move down to line 112, and be combined, like:
`after :updated, :check_configs, 'newrelic:notice_deployment'`
Otherwise, I'd place this just after 112 to keep all the after updated calls in the same place.

2018-06-01 18:31 UTC, awead commented
@informaticianme looks good. Can you squash your commits? Did you verify this works in QA?

2018-06-01 21:21 UTC, informaticianme commented
I did test this out on QA, then incorporated Adam's recommendation, however I need to adjust something else for this PR before merging. I'm closing this and will submit another PR once I've completed the adjustment.

2018-06-01 21:21 UTC, closed without merging