Add files to fedora as external files
psu-libraries/scholarsphere-3 pull request #1264
Opened 2018-05-31 14:34 UTC by little9

Test for fedora re-direct -- if they have been
added correctly, Fedora should re-direct the
request.

Redefine the predicate for `mime_type` on the
`MetadataNode` class in the Samvera stack so
it does not conflict with the Fedora mime_type,
which is used to handle external content.

Encapsulate behavior behind the environment variable
`ENV['REPOSITORY_EXTERNAL_FILES']`. If that is set
to true the new behavior will be used. If it isn't set
to true or is missing, the old behavior will be used.

If it is true the `ENV['REPOSITORY_FILESTORE_HOST']` and
`ENV['REPOSITORY_FILESTORE']` environment variables must also
be set. See the `rails_helper` for an example of how
to set the variables.

2018-05-31 16:29 UTC, awead requested changes

2018-05-31 16:29 UTC, awead commented on app/jobs/ingest_file_job.rb
> +module ActiveFedora
Are you overriding AF here? This should go under `config/initializers`

2018-05-31 16:29 UTC, awead commented on config/initializers/custom_mime_type_predicate.rb
> +Hydra::PCDM::File
Does this do anything? It doesn't seem to set any variable or call a method.

2018-05-31 16:29 UTC, awead commented on spec/spec_helper.rb
> +
can this go in a separate file under `spec/support`. It'll get loaded automatically with rspec_helper.

2018-05-31 16:47 UTC, little9 commented on config/initializers/custom_mime_type_predicate.rb
> +Hydra::PCDM::File
@no-reply could you say a little about this? It's not being instantiated, but needs to be loaded?

2018-05-31 16:47 UTC, little9 commented on spec/spec_helper.rb
> +
Ah ok!

2018-05-31 16:47 UTC, little9 commented on app/jobs/ingest_file_job.rb
> +module ActiveFedora
👍

2018-05-31 17:28 UTC, no-reply commented on config/initializers/custom_mime_type_predicate.rb
> +Hydra::PCDM::File
`Hydra::PCDM::File` includes `WithMetadata`, and it appears that it has to be the *first* thing in the application to do so. If we touch `WithMetadata` before `Hydra::PCDM::File` does, we get various errors related to the redefinition of `.properties`. This just makes sure that `Hydra::PCDM::File` is autoloaded before we force autoload of `WithMetadata` and do our work here.

2018-05-31 17:31 UTC, no-reply commented on config/initializers/custom_mime_type_predicate.rb
> +Hydra::PCDM::File
The comment attempts to clarify this. Can we polish it up so this can be better understood by newcomers?

2018-05-31 17:34 UTC, no-reply commented
See also: https://github.com/samvera/active_fedora/pull/1315

2018-05-31 17:47 UTC, awead commented on config/initializers/custom_mime_type_predicate.rb
> +Hydra::PCDM::File
Ok, that makes sense. Maybe edit the comment to, "Call the clas `Hydra::PCDM::File` without any method invocation because it includes `WithMetadata` and we need to resolve it before the method redefinition happens"

2018-05-31 19:08 UTC, bess commented
Looks like that coveralls number is only for the feature test suite -- is that a concern? Do you have suggestions for how to increase it? I feel like our PR is pretty well tested but we are open to suggestions.

2018-06-01 16:07 UTC, awead commented
@bess you can generally ignore the coveralls report, it's the code climate report that's important. It's statistics are for the combined feature and unit builds.

2018-06-01 16:16 UTC, awead requested changes
One other small change. Otherwise, this looks good to go.

2018-06-01 16:16 UTC, awead commented on spec/rails_helper.rb
> +
@little9 I made a comment here earlier, but must have forgotten to add it and it got lost...

We use the Figaro gem to manage env variables. You should add thse variables to `config/sample/application.yml`.
Then `cp config/sample/application.yml config/application.yml` to get them locally. That will allow your test suite to run locally. It also happens in the travis script as well.

2018-06-01 18:59 UTC, little9 commented on spec/rails_helper.rb
> +
Thanks! We'll add this

2018-06-05 17:25 UTC, closed without merging

2018-06-05 20:24 UTC, atz commented on app/jobs/ingest_file_job.rb
> +    ensure_repository_filestore_exists
This seems like a bunch of stuff better suited to a `before_perform` block, i.e. preconditions.

2018-06-05 20:26 UTC, atz commented on app/jobs/ingest_file_job.rb
> +    @file_set.title = [local_file.original_name]
These `@` symbols here (and in subsequent methods) seem out of place.  You declared the `attr_reader`, so the most conventional invocation would be to use it (especially below).