Add files to fedora as external files
psu-libraries/scholarsphere-3 pull request #1271
Opened 2018-06-05 17:29 UTC by little9

Test for fedora re-direct -- if they have been
added correctly, Fedora should re-direct the
request.

Redefine the predicate for `mime_type` on the
`MetadataNode` class in the Samvera stack so
it does not conflict with the Fedora mime_type,
which is used to handle external content.

Encapsulate behavior behind the environment variable
`ENV['REPOSITORY_EXTERNAL_FILES']`. If that is set
to true the new behavior will be used. If it isn't set
to true or is missing, the old behavior will be used.

If it is true the `ENV['REPOSITORY_FILESTORE_HOST']` and
`ENV['REPOSITORY_FILESTORE']` environment variables must also
be set. See the `rails_helper` for an example of how
to set the variables.

This also overrides `ActiveFedora::File`, `Hydra::Core::DownloadBehaviour`
and `CurationConcerns::WorkingDirectory` to get download functionality
working correctly.

2018-06-05 18:16 UTC, bess commented on app/jobs/ingest_file_job.rb
> +    copy_object_to_repository_filestore
We should check for REPOSITORY_EXTERNAL_FILES and only write the file if it's true.

2018-06-05 18:17 UTC, bess commented on app/jobs/ingest_file_job.rb
> +    repository_file = @file_set.files.first
Will we ever have more than one file attached to a file set?

2018-06-05 18:54 UTC, awead requested changes

2018-06-05 18:54 UTC, awead commented on app/jobs/ingest_file_job.rb
> +  def self.pairtree_path(object)
I think all the class methods should really be private instance methods. I'm not seeing any of them called from outside the class.

2018-06-05 18:54 UTC, awead commented on app/jobs/ingest_file_job.rb
> +  def self.object_path(object)
Make this a private instance method.

2018-06-05 18:54 UTC, awead commented on app/jobs/ingest_file_job.rb
> +  def self.pairtree_http_path(object, filepath)
This should be a private instance method as well.

2018-06-05 18:54 UTC, awead commented on app/jobs/ingest_file_job.rb
> +      # VersionCommitter when necessary during save_characterize_and_record_committer.
Move this comment above the method defining and delete the other comment because they're the same.

2018-06-05 18:54 UTC, awead commented on app/jobs/ingest_file_job.rb
> +
Make all methods after `perform` private. You should be able to remove the tests for them if the lines are getting covered by other tests.

2018-06-05 18:54 UTC, awead commented on config/initializers/download_behavior.rb
> +
@little9 You're overriding too much here. We already have a DownloadsController at that includes the DownloadBehavior module. If you need to check you can use ancestors:

```
> DownloadsController.ancestors
=> [DownloadsController, CurationConcerns::DownloadBehavior, Hydra::Controller::DownloadBehavior, ...]
```

What I would do here is create a new module that encapsulates only the changes you need to make to the module.
Something like:

``` ruby
# This module overrides certain methods in Hydra::Controller::DownloadBehavior to enable downloading of
# external content in Fedora.
module ExternalDownloadBehaviors

  def show
    if file.new_record?
      render_404
    else
      send_data file.content.read, type: file.mime_type, filename: file_name
    end
  end

  # and whatever additional methods need to change from the module
end
```

Then include this module in DownloadsController:

``` ruby
class DownloadsController < ApplicationController
  include CurationConcerns::DownloadBehavior
  include ExternalDownloadBehaviors

  [...]
```

Including the module after CurationConcerns::DownloadBehavior, which itself includes Hydra::Controller::DownloadBehavior,
will override the methods in DownloadBehavior.

2018-06-05 18:54 UTC, awead commented on config/initializers/working_directory.rb
> +
@little9 Instead of overriding the entire service, use a prepend. This is similar to the strategy above with
DownloadBehavior, but because we don't a defining class with included modules that define behaviors, we can
use the prepend function to inject overrides into an existing class.

For example, define a module that has on the changes you want to make to WorkingDirectory, and put this
under `app/prepends/prepended_services`:

``` ruby
# This module overrides CurationConcerns::WorkingDirectory to provide support for external files.
module PrependedServices::WithExternalFileSupport

  def copy_file_to_working_directory(file, id)
    file_name = file.respond_to?(:original_filename) ? file.original_filename.match(/[^\/]+$/)[0] : ::File.basename(file)
    copy_stream_to_working_directory(id, file_name, file)
  end

  def copy_repository_resource_to_working_directory(file, id)
    Rails.logger.debug "Loading #{file.original_name} (#{file.id}) from the repository to the working directory"
    # TODO: this causes a load into memory, which we'd like to avoid
    copy_stream_to_working_directory(id, file.original_name, file.content)
  end

  private

    def copy_stream_to_working_directory(id, name, stream)
      working_path = full_filename(id, name)
      Rails.logger.debug "Writing #{name} to the working directory at #{working_path}"
      FileUtils.mkdir_p(File.dirname(working_path))
      stream.rewind
      IO.copy_stream(stream, working_path)
      working_path
    end

end
```

Note that the above module only includes the methods that you've changed in CurationConcerns::WorkingDirectory.

Then, prepend the existing CurationConcerns::WorkingDirectory class with your module in config/application.rb:

```
  CurationConcerns::WorkingDirectory.prepend PrependedServices::WithExternalFileSupport
```

2018-06-05 18:57 UTC, awead commented on app/jobs/ingest_file_job.rb
> +    repository_file = @file_set.files.first
@bess this is a good question. Is `files.first` always the external file? Shouldn't it be `original_file`? There is `extracted_content` which is text content extracted from pdfs that's also stored in Fedora.

2018-06-06 02:47 UTC, little9 commented on config/initializers/download_behavior.rb
> +
Thanks for this! It was extremely helpful

2018-06-07 13:35 UTC, awead requested changes

2018-06-07 13:35 UTC, awead commented on app/controllers/downloads_controller.rb
> +  if ENV['REPOSITORY_EXTERNAL_FILES'] == 'true'
@little9 Have you tried this on the server with it set to both true and false? We're messing with loading, which can get dicey.

2018-06-08 12:26 UTC, awead approved these changes

2018-06-08 14:35 UTC, merged