Preserve the filename if given to IngestFileJob via opts
psu-libraries/scholarsphere-3 pull request #1279
Opened 2018-06-08 19:34 UTC by little9

This fixes an issue where files that are uploaded via
the versions uploader retain their temporary filename.

The inital file upload form creates a temporary file with
the original filename, but the version upload does not.

2018-06-11 18:08 UTC, carolyncole requested changes
Just a couple small changes.  Looks good overall

2018-06-11 18:08 UTC, cam156 commented on app/jobs/ingest_file_job.rb
> +    # Whenever you upload a version, the filename option is set
Should this code be moved into the if since it is not used?

2018-06-11 18:08 UTC, cam156 commented on app/jobs/ingest_file_job.rb
> +    local_file = Hydra::Derivatives::IoDecorator.new(File.open(@filepath, 'rb'))
I do not believe this change is necessary since filepath is just a attr_reader

2018-06-11 19:51 UTC, little9 commented on app/jobs/ingest_file_job.rb
> +    local_file = Hydra::Derivatives::IoDecorator.new(File.open(@filepath, 'rb'))
👍

2018-06-11 19:58 UTC, little9 commented
@cam156 thanks for the feedback! I went ahead and made the changes you suggested.

2018-06-12 13:03 UTC, cam156 commented
@little9 Unfortunately this PR conflicts with the one I just merged

2018-06-12 16:28 UTC, little9 commented
@cam156 This is back to passing after resolving the conflicts.

2018-06-12 20:34 UTC, awead submitted a review, later dismissed

2018-06-13 13:17 UTC, merged