Store files in bags on the filesystem
psu-libraries/scholarsphere-3 pull request #1281
Opened 2018-06-08 21:24 UTC by little9

This commit changes the `Pairtree` class so
that it stores files in a bag structure. The structure looks like:

```
/repository/ms/t3/ka/bc/mst3kabc
1528492618/
├── bag-info.txt
├── bagit.txt
├── data
│   └── world.png
├── manifest-md5.txt
├── manifest-sha1.txt
├── tagmanifest-md5.txt
└── tagmanifest-sha1.txt                                                            
```

So you have as root repistory folder, a pairtree for the idenitifier,
a unix timestamp for versioning, which is a bag.

This change uses the ruby bagit library to create the bag:
https://github.com/tipr/bagit

2018-06-11 18:18 UTC, carolyncole requested changes
The build is failing and a few comments

2018-06-11 18:18 UTC, cam156 commented on spec/lib/scholarsphere/pairtree_spec.rb
> +        # FileUtils.rm_rf(ENV['REPOSITORY_FILESTORE'])
If this is undesired then can we just remove it?

2018-06-11 18:18 UTC, cam156 commented on lib/scholarsphere/pairtree.rb
>        FileUtils::cp filepath, full_path
Would it be better to just do a move?

2018-06-11 20:02 UTC, little9 commented on spec/lib/scholarsphere/pairtree_spec.rb
> +        # FileUtils.rm_rf(ENV['REPOSITORY_FILESTORE'])
Sorry, this is desired! I was checking the contents of that directory and forgot to un-comment it.

2018-06-11 20:10 UTC, little9 commented on lib/scholarsphere/pairtree.rb
>        FileUtils::cp filepath, full_path
If I do a move there, then in the test suite the `spec/fixtures/world.png` file will be deleted and subsequent tests will fail. I was assuming that you just have some of cron job that deletes temporary files on a regular basis on the server. Moving wouldn't be more efficient here because it just combines the copy and delete/unlink operations.

2018-06-12 12:58 UTC, carolyncole approved these changes

2018-06-12 12:58 UTC, merged