Change all internal files versions to external files
psu-libraries/scholarsphere-3 pull request #1292
Opened 2018-06-13 16:33 UTC by little9

This commit includes a class that takes a Work type and
converts each of the objects to use external storage.

It does this by creating new versions of the files and deleting
the old versions. The version slugs created by ActiveFedora are
preserver. 'version1' remains 'version1' after the conversion.
The version number is retained by setting an env variable that
is checked by the overridden `version_name` method in
`ActiveFedora::File`. Instead of incrementing it will decrement,
maintaining the correct version number as the conversion happens.

There is a rake task to run this conversion that you can run:
`rake scholarsphere:internal_to_external_files`

2018-06-13 17:32 UTC, bess requested changes

2018-06-13 17:32 UTC, bess commented on app/services/external_files_conversion.rb
> +          @file_set = work.file_sets.first
I think this is only going to convert the first `file_set` in each work.

2018-06-14 13:40 UTC, awead requested changes

2018-06-14 13:40 UTC, awead commented on spec/factory_helpers.rb
> +module FactoryHelpers
there's already a FactoryHelpers module at spec/support/helpers/factory_helper.rb. Could you add this there?

2018-06-14 13:40 UTC, awead commented on app/services/external_files_conversion.rb
> +      FileUtils.mkdir_p(Rails.root.join('tmp', 'external_internal_conversion'))
Can this be configurable in ENV? It can default to `tmp/external_internal_conversion`

2018-06-14 13:40 UTC, awead commented on app/services/external_files_conversion.rb
> +      file_path = File.absolute_path(file.path)
If we're copying the file and re-ingesting, do we have any concerns about catching any checksum errors? @cam156 ?

2018-06-15 11:36 UTC, carolyncole reviewed
I'm assuming this is still a work in progress, but I added some comments.

2018-06-15 11:36 UTC, cam156 commented on app/services/external_files_conversion.rb
>    def initialize(work)
This attribute should also be renames to indicate you are looking for a class

2018-06-15 11:36 UTC, cam156 commented on app/services/external_files_conversion.rb
> +          ActiveFedora.fedora.connection.post(file.uri + '/fcr:versions', nil, slug: 'auto_placeholder')
can we add a comment here to indicate that the auto is important in the name?

2018-06-15 11:36 UTC, cam156 commented on app/services/external_files_conversion.rb
> +    def filename_from_content_disposition(content_disposition)
My preference for reading would be to have this method after the method that uses it.

2018-06-15 11:36 UTC, cam156 commented on app/services/external_files_conversion.rb
> +      FileUtils.mkdir_p(Rails.root.join('tmp', 'external_internal_conversion', time_stamp))
Is this going to make a different directory for each temporary file?

2018-06-15 11:36 UTC, cam156 commented on lib/tasks/scholarsphere.rake
> +    puts 'This task will create a new version of all the works.'
👍

2018-06-15 11:36 UTC, cam156 commented on spec/support/helpers/factory_helpers.rb
> +  extend self
What does this do?

2018-06-15 12:17 UTC, cam156 commented
Also could you rebase against develop?  @awead added another build so travis checks both with and without external files.

2018-06-15 13:49 UTC, little9 commented on app/services/external_files_conversion.rb
> +      FileUtils.mkdir_p(Rails.root.join('tmp', 'external_internal_conversion', time_stamp))
Yeah, this is so that names don't collide

2018-06-15 13:53 UTC, little9 commented on app/services/external_files_conversion.rb
> +          ActiveFedora.fedora.connection.post(file.uri + '/fcr:versions', nil, slug: 'auto_placeholder')
👍

2018-06-15 13:53 UTC, little9 commented on app/services/external_files_conversion.rb
> +    def filename_from_content_disposition(content_disposition)
👍

2018-06-15 14:10 UTC, bess approved these changes
:+1:

2018-06-15 15:10 UTC, little9 commented on spec/support/helpers/factory_helpers.rb
> +  extend self
It makes all of the methods instance methods for the class the includes the module

2018-06-15 19:15 UTC, carolyncole approved these changes

2018-06-15 19:15 UTC, carolyncole commented on app/services/external_files_conversion.rb
> +    @work_class.all.each do |work|
Can we check to see if the file is external and not do a conversion if it is already external.

2018-06-15 19:15 UTC, carolyncole commented on app/services/external_files_conversion.rb
> +          end
Rescue any exception and put out an error log, and a way to restart

2018-06-18 16:29 UTC, merged