Convert a single object
psu-libraries/scholarsphere-3 pull request #1339
Opened 2018-08-16 20:41 UTC by bess

If we can convert a single object from internal to
external files storage, instead of having to convert
all of the objects of a given class, it will make it
much faster to debug configuration issues.

Connected to #1338

2018-08-16 20:45 UTC, awead requested changes

2018-08-16 20:45 UTC, awead commented on app/services/external_files_conversion.rb
> +    @opts = opts
@bess where does `opts` get used?

2018-08-17 13:26 UTC, bess commented on app/services/external_files_conversion.rb
> +    @opts = opts
Whoops, that was an approach I started to take but then decided to go a different way. I'll remove it.

2018-08-23 18:12 UTC, bess commented
Reopening elsewhere

2018-08-23 18:12 UTC, closed without merging