Better processing of term queries in Solr
psu-libraries/scholarsphere-3 pull request #1353
Opened 2018-08-22 15:29 UTC by awead

Increases test coverage for TermQuery and handles any exception that
might be returned from RSolr.

Related to #1175

2018-08-23 16:01 UTC, carolyncole requested changes

2018-08-23 16:01 UTC, cam156 commented on spec/services/sufia/term_query_spec.rb
> +      expect(term.query).to eq([])
@awead since you are not getting any values here, you should also check to be certain an error message is not being logged.

2018-08-23 16:01 UTC, cam156 commented on app/prepends/prepended_services/with_null_term_query.rb
> +    Rails.logger.error "Unable query Solr for term #{term}: #{exception}"
`Unable to query Solr` might be better grammatically.

2018-08-27 19:38 UTC, awead commented
@cam156 this is fixed up.

2018-08-29 15:50 UTC, merged