When bagging file don't read the whole file into memory
psu-libraries/scholarsphere-3 pull request #1379
Opened 2018-08-30 16:39 UTC by little9

This changes the bagger class so that it doesn't
read the whole file into memory when sending the
file to BagIt. Instead it sends the data a line at a
time.

2018-08-30 16:59 UTC, awead requested changes

2018-08-30 16:59 UTC, awead commented on lib/scholarsphere/bagger.rb
> +        IO.foreach(working_file).each { |line| io.puts line }
@little9 Will this work with binary data?

2018-08-31 13:58 UTC, little9 commented on lib/scholarsphere/bagger.rb
> +        IO.foreach(working_file).each { |line| io.puts line }
@awead it does work with binary data, I'll add a test to this PR to illustrate

2018-08-31 15:36 UTC, little9 commented on lib/scholarsphere/bagger.rb
> +        IO.foreach(working_file).each { |line| io.puts line }
@awead This PR now includes a spec that shows that this is working as one would expect. It makes two bags, one for text data and one for bin data and compares the SHAs in the bag with the correct SHA.

2018-08-31 15:56 UTC, awead approved these changes

2018-08-31 17:56 UTC, merged