Check that checksums remain the same during conversion
psu-libraries/scholarsphere-3 pull request #1391
Opened 2018-09-05 18:14 UTC by little9

This adds a class that when given a work, returns an
array with all the checksums for all versions of the files
in that work. This is used in the conversion class
before the conversion and after the conversion.

If these checksums don't match, an error is logged.

2018-09-05 19:00 UTC, bess requested changes
Hey, Jamie. Let's talk about this. I don't think the Fedora checksum is re-calculating the checksum of the file after it's been written to disk. I'd be very happy to be wrong on that, but that was my understanding from conversations with Esmé. So I think that post-migration we have to explicitly recalculate the checksum against the file on disk.

2018-09-05 20:27 UTC, little9 commented
@bess I updated this so that it compares against a re-calculated check sum.

2018-09-05 21:17 UTC, bess approved these changes
👍 🚀

2018-09-06 11:15 UTC, cam156 commented
@little9 It looks like the tests do not pass on Travis.  I am not certain why, but the checksums are not the same.

2018-09-06 23:42 UTC, cam156 commented
I tried this branch on QA and got this error:
```
2018-09-06 19:37:58 -0400 (31440) Starting to convert work 8s45q881f
2018-09-06 19:38:40 -0400 (31440) error migrating object: 8s45q881f; redirection forbidden: http://scholarsphere-repo-qa.libraries.psu.edu:8080/SSqaFedora/rest/prod/3x/s5/5m/95/3xs55m9505/files/5bd5b892-d65f-43b8-8355-3759469ccada/fcr:versions/version1 -> https://scholarsphere-qa.libraries.psu.edu/binaries/3x/s5/5m/95/3xs55m9505/1536277087/data/3xs55m9505_version1_Andragogy_and_Technology_pdf.pdf
```

2018-09-06 23:44 UTC, little9 commented
@cam156 that looks like the same http/https issue that was happening earlier

2018-09-07 12:54 UTC, cam156 commented on app/services/checksummer.rb
> +          checksums << ActiveFedora::FixityService.new(version.uri).expected_message_digest.gsub('urn:sha1:', '')
I wonder if this fixity service needs to be updated to use the open with the allow http to https redirect

2018-09-07 17:17 UTC, cam156 commented on app/services/checksummer.rb
> +          checksums << ActiveFedora::FixityService.new(version.uri).expected_message_digest.gsub('urn:sha1:', '')
Just ran a quick test on QA and this line is not an issue

2018-09-07 17:19 UTC, cam156 commented on app/services/checksummer.rb
> +          open(version.uri) { |f| f.each_line { |line| sha1.update line } }
This line is the issue.  It does just a plain open.  It really needs to be 
```
open(
        file_set.original_file.uri,
          http_basic_authentication: [ActiveFedora.fedora_config.credentials['user'], ActiveFedora.fedora_config.credentials['password']],
          allow_redirections: :all
```

2018-09-07 17:34 UTC, little9 commented
@cam156 I updated the open like you suggested and pushed that changed

2018-09-10 14:07 UTC, merged