Use DataCite to mint DOIs
psu-libraries/scholarsphere-3 pull request #1495
Opened 2018-11-20 16:26 UTC by awead

Updates the ezid-client gem to support the EZ API and adds the required credentials for authentication.

We can still continue to use the current EZID API by using the appropriate `EZID_HOST` and corresponding user, password, and handle. When the time comes to switch to using DataCite's EZ API, we specify the DateCite hostname, as well as corresponding user, password, and new handle.

Connected to #1237

2018-11-20 16:53 UTC, carolyncole requested changes
@awead It would be nice to have a test that calls out to datacite to be certain that it will work when we need to transition.

2018-11-20 16:53 UTC, cam156 commented on app/services/doi_service.rb
> +  def initialize(handle = ScholarSphere::Application.config.doi_handle)
@awead how does this transition to DataCite?  Does the EzidClient just work?

2018-11-20 19:14 UTC, awead commented on app/services/doi_service.rb
> +  def initialize(handle = ScholarSphere::Application.config.doi_handle)
The ezid-client gem supports both. Just changing the hostname is all that's needed.

2018-11-20 19:15 UTC, awead commented
@cam156 should we have a test that's mocked via VCR/webmock?

2018-11-20 19:17 UTC, cam156 commented
@awead a vcr test seems like a good idea.  Did we need to do anything related to the fact that DataCite will not accept Book as a type?

2018-11-20 19:44 UTC, awead commented
@cam156 RE: VCR, I agree it would be helpful, but I'm hesitant to do it now given the changes to their test instance. Also, the VCR test wouldn't catch these changes in the future. It would however, ensure that nothing was breaking on our side, so it's still worthwhile. I'd just rather wait until we know for sure what kind of request we'll need to send to them.

2018-11-20 19:51 UTC, awead commented
@cam156 BTW, I have tested this branch locally using the current EZID host and credentials that are in production, and DOIs are getting minted. This same branch worked _last week_ before the apparent changes to DataCite's test instance. So we can be confident that this change does not break current production, but due to DataCite's changes, we'd likely have to make additional changes to mint DOI successfully.

That being said, this PR does provide "support" for both EZID and DataCite. It's just that the latter does not accept all our metadata in its present state.

2018-11-21 20:31 UTC, carolyncole approved these changes

2018-11-24 14:05 UTC, merged