updates fits conf. fixes #1587
psu-libraries/scholarsphere-3 pull request #1592
Opened 2019-07-08 20:01 UTC by whereismyjetpack

2019-07-08 20:03 UTC, awead approved these changes

2019-07-16 16:41 UTC, awead requested changes
@whereismyjetpack I left a couple of comments. You should also squash all the commits down to one.

2019-07-16 16:41 UTC, awead commented on travis/test.sh
> +# TODO fix this
It's unclear what needs to be fixed.

2019-07-16 16:41 UTC, awead commented on entrypoint.sh
> +
is this file related to the fits changes? If so, it could use some comments explaining how. Otherwise, it might need to be in another PR.

2019-07-16 16:41 UTC, awead commented on .travis.yml
> +#   - cat log/test.log
Can you uncomment these?

2019-07-16 17:00 UTC, whereismyjetpack commented on travis/test.sh
> +# TODO fix this
i'm removing the fits directory, I think we might want to remove the submodule, and then create the directory here instead of needing to remove it

2019-07-16 17:00 UTC, whereismyjetpack commented on entrypoint.sh
> +
whoops. this shouldn't be here. sorry

2019-07-16 17:00 UTC, whereismyjetpack commented on .travis.yml
> +#   - cat log/test.log
yup!

2019-07-16 19:08 UTC, whereismyjetpack commented
@awead I think this is ready to go. branch passed/ presumably the PR will as well, I can squash in the Merge interface when approved.

2019-07-16 19:20 UTC, awead approved these changes

2019-07-16 19:57 UTC, merged