Using the latest Sufia from master
psu-libraries/scholarsphere-3 pull request #372
Opened 2016-09-09 18:49 UTC by awead

There will be some, or maybe many, failures here, so this is a question. Do we want to roll with the latest and greatest in Sufia for our upcoming sprint? 7.2 should be released in a week or less, so it's likely it'll come out during the sprint. So I'm think we should just start working against it now to minimize surprises.

2016-09-26 17:30 UTC, awead commented
@cam156 this is ready to go. I've pushed up the latest commit from Sufia as of today. I've marked one test pending because of a peculiar failure that I've outlined in https://github.com/psu-stewardship/scholarsphere/pull/372.

2016-09-26 18:44 UTC, cam156 commented on config/authorities/licenses.yml
> +terms:
@awead I think we should just rename rights.yml instead of adding a new file.

2016-09-26 18:45 UTC, cam156 commented on spec/features/batch_edit_spec.rb
> +    xit 'edits each field and displays the changes', js: true do
@awead Is this the intentionally pending test?

2016-09-26 18:49 UTC, cam156 commented on spec/presenters/stats_presenter_spec.rb
> +    let(:users_count)    { ::User.count }
This seems like it might be testing zero.  You should create a user to make sure it does not always return zero.

2016-09-26 18:51 UTC, carolyncole requested changes
Looks good overall.  Seems like you have 3 new tests that are pending.  One that you changes the it to xit, one marked pending and one that was commented out that is now pending.

2016-09-26 19:33 UTC, awead commented on config/authorities/licenses.yml
> +terms:
It was changed in Sufia. I can just remove the rights.yml file.

2016-09-26 19:33 UTC, awead commented on spec/features/batch_edit_spec.rb
> +    xit 'edits each field and displays the changes', js: true do
Yes, batch edit is misbehaving as well.

2016-09-27 14:02 UTC, carolyncole approved these changes

2016-09-27 14:02 UTC, merged