Reconfiguring test suite to use Rspec rails_helper file
psu-libraries/scholarsphere-3 pull request #395
Opened 2016-10-11 15:45 UTC by awead

By default, new Rspec installations within a Rails application create a spec_helper file and a rails_helper file. Errors can arise if the latter is not present. Additionally, the updated spec_helper file enables `verify_partial_doubles` which caused new failures because we were mocking methods that no longer existed on the test subject. The tests have been corrected, and now with the newly-enabled option, if we mock methods that aren't present in the test subject, the test will fail.

FYI, @cam156 @mtribone

2016-10-11 16:09 UTC, carolyncole requested changes
Overall looks great!  Not sure why an entire test got removed.

2016-10-11 16:09 UTC, cam156 commented on spec/views/catalog/_index_default.html.erb_spec.rb
> -describe "catalog/_index_default.html.erb" do
@awead Why are you removing this test?

2016-10-11 16:09 UTC, cam156 commented on spec/controllers/catalog_controller_spec.rb
> -    allow_any_instance_of(GenericWork).to receive(:characterize_if_changed).and_yield
@awead Curious why you removed this?

2016-10-11 17:04 UTC, awead commented on spec/controllers/catalog_controller_spec.rb
> -    allow_any_instance_of(GenericWork).to receive(:characterize_if_changed).and_yield
This is what I talking about by enabling `verify_partial_doubles`. The `characterize_if_changed` doesn't exist anymore and now the test fails because we're mocking a method that doesn't existing anymore.

2016-10-11 17:08 UTC, awead commented on spec/views/catalog/_index_default.html.erb_spec.rb
> -describe "catalog/_index_default.html.erb" do
Because of `verify_partial_doubles`, the test fails because that view doesn't implement `blacklight_configuration_context`. I believe this is because we're not directly overriding this view. In any case, the test criteria was moved to spec/features/catalog_spec.rb. Incidentally, the view test was passing when it should have been failing because the titles do in fact appear in the search results when in gallery view, and the test was asserting that they did not.

2016-10-14 16:41 UTC, carolyncole approved these changes

2016-10-14 16:41 UTC, merged