Fluid container and spacing
psu-libraries/scholarsphere-3 pull request #426
Opened 2016-10-26 14:26 UTC by mtribone

Fixes container on home page and 1 column layout from CC to be container-fluid.

2016-10-26 14:27 UTC, mtribone commented
![screen shot 2016-10-26 at 10 25 21 am](https://cloud.githubusercontent.com/assets/4163828/19729981/bd9c6f56-9b66-11e6-83fc-0ba345d01b85.png)

2016-10-26 14:27 UTC, mtribone commented
![screen shot 2016-10-26 at 10 25 42 am](https://cloud.githubusercontent.com/assets/4163828/19729986/c4da6f8e-9b66-11e6-92e4-824820e471ae.png)

2016-10-26 17:28 UTC, carolyncole reviewed
Is this change just about adding "container-fluid" to the content-wrapper div?

Could we just add that via javascript?

```
document.getElementById('content-wrapper').classList.add('container-fluid');
```

Or add some TODOs at the beginning of the class with a ticket in sufia so we can stop maintaining this code at some point.

2016-10-26 17:44 UTC, mtribone commented
We certainly could just add it via javascript. I'd have to remove the class `container` and add the class `container-fluid`

2016-10-27 11:12 UTC, carolyncole requested changes

2016-10-27 11:12 UTC, cam156 commented on app/assets/javascripts/scholarsphere_layout.js
> +/**
@mtribone You likely need the BlackLight.onload like here: https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/batch.js#L1
and then close like here: https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/batch.js#L13

2016-10-27 11:12 UTC, cam156 commented on app/assets/javascripts/scholarsphere_layout.js
> +document.getElementById('content-wrapper').classList.add('container-fluid');
You can also remove a class.  Here is the jquery syntax for adding and removing a class

`$( "#content-wrapper" ).removeClass( "container" ).addClass( "container-fluid" );`

So the entire file would look more like:

```
Blacklight.onLoad(function() {
   $( "#content-wrapper" ).removeClass( "container" ).addClass( "container-fluid" );
});
```

2016-10-27 17:54 UTC, awead commented on app/assets/javascripts/scholarsphere_layout.js
> +/**
changes approved!

2016-10-27 17:54 UTC, merged