DISCUSSION, Don't Merge: Cleanup creator and other facets prior to indexing
psu-libraries/scholarsphere-3 pull request #655
Opened 2017-02-15 20:45 UTC by awead

This is a solution to #632. I'm not too keen on it.

The initial solution is simple: cleanup facet terms before sending them to solr such that _ADAM WEAD_ becomes _Adam Wead_. However, it gets complicated because we have linked facets, urls that map to catalog searches with a given faceted search. Because we've changed the facet but not the actual value the user entered, the links don't work.

The solution then is to modify the links so that they display the original user's entered text, but link to the modified facet term.

This is kind of icky because we're essentially modifying twice: first on the way in (to Solr) and then on the way out again when we display. The solution below could be made more efficient, perhaps. But it strikes me that the _ideal_ solution might be to modify the user input in the first place, normalizing values upfront.

Thoughts? @cam156 @olendorf ?

2017-02-16 12:41 UTC, cam156 commented on app/services/solr_document_groomer.rb
> +    document[Solrizer.solr_name('creator', :facetable)] = clean_names
@awead I was thinking our changes would be Additive, not changing.  
```
document[Solrizer.solr_name('creator_cleaner', :facetable)] = clean_names
```
We would then just use that for our facets and leave the original documents alone.

2017-02-21 16:13 UTC, awead commented
ping @cam156 This is ready for review now. Note, I've added another commit for #659. I will also be doing a separate PR and ticket to address the cleanup of spaces in fields because it's really separate from the scope of this ticket. Let me know what you think.

2017-02-21 16:39 UTC, carolyncole requested changes

2017-02-21 16:39 UTC, cam156 commented on app/services/field_configurator.rb
> +      creator: FieldConfig.new(label: "Creator", facet_values: [:titleize]),
@awead 'facet_values' name really threw me.  facet_cleaner_methods or facet_value_cleaners might be a better name.   When I saw the name facet_values in the code above I could not understand why you were calling send on a value of the facet.

2017-02-21 16:39 UTC, cam156 commented on app/services/field_configurator.rb
> -      common_fields).merge(contributor: FieldConfig.new("Contributor"),
@awead why did contributor get removed from the index?  Was this planned?

2017-02-21 16:39 UTC, cam156 commented on app/views/curation_concerns/base/_attribute_rows.html.erb
> +<%= presenter.attribute_to_html(:publisher, render_as: :valued_facet, facet_values: presenter.facet_values(:publisher)) %>
@awead here it seems like the facet_values is the actual value.  Is that correct?

2017-02-21 16:39 UTC, cam156 commented on spec/presenters/work_show_presenter_spec.rb
> +    it { is_expected.to eq("JOE SMITH" => "Joe Smith") }
Here is a good example of my confusion. This line is actual values, and `https://github.com/psu-stewardship/scholarsphere/pull/655/files#diff-ee51de3cf9faf45a5042f3c4059047f1R59` for the same name is cleaning methods.

2017-02-21 16:47 UTC, awead commented on app/services/field_configurator.rb
> -      common_fields).merge(contributor: FieldConfig.new("Contributor"),
@cam156 it didn't. It's been moved to common_fields so it can be both an index and facet field. See #659

2017-02-21 16:49 UTC, awead commented on spec/presenters/work_show_presenter_spec.rb
> +    it { is_expected.to eq("JOE SMITH" => "Joe Smith") }
@cam156 good point. I'll change the config key to be something like `:facet_value_cleaners` and leave the presenter method as `facet_values` because it is returning actual values there.

2017-02-22 12:20 UTC, carolyncole approved these changes

2017-02-22 12:20 UTC, merged