return batches with only one item since there are no relations to be made
psu-libraries/scholarsphere-3 pull request #662
Opened 2017-02-22 12:02 UTC by cam156

Additionally the save is not needed, the tests pas with or without it.

This is an effort to make the batch processing faster.  It may or may not make larger batches faster.

2017-02-22 20:39 UTC, awead requested changes

2017-02-22 20:39 UTC, awead commented on lib/scholarsphere/import/batch_translator.rb
> +        return if work_ids.length <= 1 # no relations unless we have atleasrt two works
how about `# skip anything that doesn't have at least two works`

2017-02-23 15:48 UTC, cam156 commented
@awead updated the comment and the code to reflect your suggested change

2017-02-23 16:02 UTC, awead approved these changes

2017-02-23 19:51 UTC, merged