Reorganize local JS code; remove unused file upload options
psu-libraries/scholarsphere-3 pull request #669
Opened 2017-02-23 19:00 UTC by awead

This is a very simple solution. Also, I don't think it's possible to test as a feature and would have to use Jasmine since we're submitting and Capybara is going to wait for the page to load.
![temp](https://cloud.githubusercontent.com/assets/312085/23274338/60b0c13e-f9d0-11e6-8b1d-648984491353.png)

2017-02-24 17:37 UTC, carolyncole requested changes
@awead looks good to me.  I like that it speaks!  Just a couple little tweaks.

2017-02-24 17:37 UTC, cam156 commented on app/assets/javascripts/scholarsphere_fileupload.js
> -max_file_size = 500000000;
@awead why did you remove the maximums?  These override items in curation concerns https://github.com/projecthydra/curation_concerns/blob/master/app/assets/javascripts/curation_concerns/uploader.js#L13

2017-02-24 17:37 UTC, cam156 commented on app/views/curation_concerns/base/_form_progress.html.erb
> +<aside id="form-progress" class="form-progress panel panel-default">
Can you add a comment to the top of the class to describe why we are overriding?

2017-02-24 17:47 UTC, awead commented on app/assets/javascripts/scholarsphere_fileupload.js
> -max_file_size = 500000000;
@cam156 these don't do anything anymore. The size restriction is now in:
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/assets/javascripts/sufia/uploader.js#L34-L35

2017-02-24 19:13 UTC, mtribone commented on app/views/curation_concerns/base/_form_progress.html.erb
> +      <div class="progress-bar progress-bar-striped active" style="width: 100%">
Can the inline style for the width be applied to a class that you are using?

2017-02-24 19:44 UTC, awead commented on app/views/curation_concerns/base/_form_progress.html.erb
> +<aside id="form-progress" class="form-progress panel panel-default">
@cam156 I put the comment above the spot at which we're overriding.

2017-02-24 19:45 UTC, awead commented on app/views/curation_concerns/base/_form_progress.html.erb
> +      <div class="progress-bar progress-bar-striped active" style="width: 100%">
@mtribone done.

2017-02-27 12:01 UTC, carolyncole approved these changes

2017-02-27 12:01 UTC, merged