Description and keyword are required for collections, ref #674
psu-libraries/scholarsphere-3 pull request #701
Opened 2017-03-10 18:22 UTC by awead

2017-03-16 11:25 UTC, carolyncole requested changes

2017-03-16 11:25 UTC, cam156 commented on spec/forms/collection_form_spec.rb
> +    it { is_expected.not_to include(:title, :description, :keyword) }
@awead It would be better to check for exactly what we are expecting.  This test will allow any other terms including adding or removing existing terms.  We will want to know if that changes down the road.

2017-03-16 11:25 UTC, cam156 commented on spec/features/collection/create_spec.rb
> +        fill_in "Description", with: "description"
I wonder if these lines could be added into the before since they are set up and repeated for each test.

2017-03-16 13:07 UTC, awead commented on spec/forms/collection_form_spec.rb
> +    it { is_expected.not_to include(:title, :description, :keyword) }
@cam156 these fields were under secondary terms prior to this change, hence the reason to ensure they are not there now, but I can check for the remaining terms as well.

2017-03-17 13:49 UTC, carolyncole approved these changes

2017-03-17 13:49 UTC, merged