Add Optional Steps to Save Viz Widget
psu-libraries/scholarsphere-3 pull request #711
Opened 2017-03-20 18:53 UTC by mtribone

Adds optional metadata links to save widget, adds tab names to JS file, and adds css for better spacing.

![screen shot 2017-03-20 at 2 51 27 pm](https://cloud.githubusercontent.com/assets/4163828/24116358/ed97b35e-0d7c-11e7-8f07-7fbc1a129545.png)

2017-03-21 15:47 UTC, carolyncole requested changes
@mtribone it would be nice to add a test (or add to a test to click on your new links).  That way if they get removed the tests would fail.  Otherwise looks good.

2017-03-21 15:52 UTC, mtribone commented
@cam156 👍

2017-03-21 17:07 UTC, mtribone commented on spec/features/generic_work/upload_and_delete_spec.rb
> +        # Check for optional metadata
@cam156 I've basically just added a click, but did not add any tests for content on each tab. Yes?

2017-03-22 15:15 UTC, carolyncole approved these changes

2017-03-22 15:50 UTC, merged