Updates help text for both works and collections.
psu-libraries/scholarsphere-3 pull request #746
Opened 2017-04-10 20:27 UTC by mtribone

![screen shot 2017-04-10 at 4 19 08 pm](https://cloud.githubusercontent.com/assets/4163828/24881032/8516fe22-1e0a-11e7-891c-a0045bec51ea.png)

2017-04-10 20:27 UTC, mtribone commented
![screen shot 2017-04-10 at 4 18 04 pm](https://cloud.githubusercontent.com/assets/4163828/24881046/92d12fce-1e0a-11e7-86f4-a420169b1681.png)

2017-04-11 16:25 UTC, awead requested changes

2017-04-11 16:25 UTC, awead commented on config/locales/sufia.en.yml
> +        rights: "Licensing and distribution information governing access to the work. A rights statement or license ensures your work gets used appropriately and that you get credit when your work is
@mtribone do you mean collection here instead of work?

2017-04-11 17:57 UTC, mtribone commented on config/locales/sufia.en.yml
> +        rights: "Licensing and distribution information governing access to the work. A rights statement or license ensures your work gets used appropriately and that you get credit when your work is
Yes, indeed, I meant collection.

2017-04-11 18:58 UTC, awead approved these changes

2017-04-11 19:01 UTC, merged