Removing unused static pages; refactor existing tests
psu-libraries/scholarsphere-3 pull request #757
Opened 2017-04-12 14:21 UTC by awead

This addresses #728, but as far as I can tell, the videos aren't there anymore. However, there are some other things that need cleaning up. There are some static pages that aren't used anymore: error_pages and subject_libraries. I can find no links to these pages and they aren't tested anywhere.

I've also edited the help page to remove the internal anchor links. The page is too short for them to be effective. I've also removed all of the commented-out html code.

The feature tests have been updated to reflect the existing pages.

2017-04-13 12:58 UTC, carolyncole requested changes
Looks like you are removing an accessibility item.

2017-04-13 12:58 UTC, cam156 commented on app/views/static/help.html.erb
> -<h2> Table of Contents</h2>
@awead This was added for accessibility.  We still have other sections so removing this make the page less accessible.

2017-04-13 12:58 UTC, cam156 commented on app/views/static/subject_libraries.html.erb
> -<h1> Subject Libraries </h1>
@awead Have you looked at google scholar to see if this page is accessed?

2017-04-13 13:28 UTC, awead commented on app/views/static/subject_libraries.html.erb
> -<h1> Subject Libraries </h1>
No, how do I do that?

2017-04-13 13:28 UTC, awead commented on app/views/static/help.html.erb
> -<h2> Table of Contents</h2>
Could we hide it then? It doesn't do anything for sighted users, other than reload the page.

2017-04-13 14:09 UTC, awead commented on app/views/static/help.html.erb
> -<h2> Table of Contents</h2>
@cam156 I thought the headings themselves outlined the structure, which is what we're doing with the other pages, ensuring that headings move from H1, H2, etc. With the screen reader on, I can get an overview of the page just from the headings:
![help](https://cloud.githubusercontent.com/assets/312085/25008279/3a89e7ce-2031-11e7-8b44-26025ccd1721.png)

2017-04-13 14:16 UTC, awead commented on app/views/static/subject_libraries.html.erb
> -<h1> Subject Libraries </h1>
@cam156 looks like it was removed at some point in QA: https://scholarsphere-qa.dlt.psu.edu/subject_libraries
It's still working in prod: https://scholarsphere.psu.edu/subject_libraries

2017-04-13 15:17 UTC, awead commented
@cam156 We agreed that subject_libraries could be removed. I put the TOC back into the help page.  Thanks!

2017-04-14 10:57 UTC, carolyncole approved these changes

2017-04-14 10:57 UTC, merged