Work vs Collection Help Text
psu-libraries/scholarsphere-3 pull request #782
Opened 2017-04-24 18:57 UTC by mtribone

Adjusts text for new work and adds work vs collection text to new collection to be consistent.

2017-04-24 18:57 UTC, mtribone commented
![screen shot 2017-04-24 at 2 11 26 pm](https://cloud.githubusercontent.com/assets/4163828/25353756/5efb8fba-28fe-11e7-8bfb-706df224e16b.png)

2017-04-24 18:57 UTC, mtribone commented
![screen shot 2017-04-24 at 2 10 54 pm](https://cloud.githubusercontent.com/assets/4163828/25353763/6686e2ac-28fe-11e7-869e-350a2b54a893.png)

2017-04-24 19:41 UTC, awead requested changes

2017-04-24 19:41 UTC, awead commented on app/views/collections/new.html.erb
> +<p class="instructions"><%= t("sufia.batch_uploads.files.concepts") %></p>
@mtribone shouldn't this have it's own entry? The text for `sufia.batch_uploads.files.concepts` doesn't seem appropriate for collections.

2017-04-24 19:44 UTC, mtribone commented on app/views/collections/new.html.erb
> +<p class="instructions"><%= t("sufia.batch_uploads.files.concepts") %></p>
The text is exactly the same. If I give it its own entry we'll need to change it twice. Perhaps a better thing would be to pull it out of batch_uploads and put it in a more generic place?

2017-04-24 19:56 UTC, awead commented on app/views/collections/new.html.erb
> +<p class="instructions"><%= t("sufia.batch_uploads.files.concepts") %></p>
@mtribone Maybe I'm misunderstanding, but here's what I figure that page will show:

# Create New Collection
A work consists of one or more files that work together as a functional unit [...]

I thought the idea was to explain what collections are. Why are we describing what a work is if we're creating collections?

2017-04-24 19:57 UTC, awead commented on app/views/collections/new.html.erb
> +<p class="instructions"><%= t("sufia.batch_uploads.files.concepts") %></p>
duh. sorry, screenshot is above. So, yeah, all I'm saying is it looks odd to be talking about works when you're on a collections creation page.

2017-04-24 20:05 UTC, mtribone commented on app/views/collections/new.html.erb
> +<p class="instructions"><%= t("sufia.batch_uploads.files.concepts") %></p>
Yeah I can see that point. I was asked today to add the same help text for consistency.

2017-04-24 20:11 UTC, mtribone commented
New collection help text


![screen shot 2017-04-24 at 4 10 01 pm](https://cloud.githubusercontent.com/assets/4163828/25356571/a7fe9090-2908-11e7-8fe6-e51e0190dcd0.png)

2017-04-25 13:43 UTC, mtribone commented
![screen shot 2017-04-25 at 9 42 38 am](https://cloud.githubusercontent.com/assets/4163828/25388332/9befe14e-299b-11e7-87e0-946346282568.png)

2017-04-25 14:42 UTC, awead approved these changes

2017-04-25 14:42 UTC, merged