Fix issue with capturing and rendering Google Analytics info, ref #842
psu-libraries/scholarsphere-3 pull request #852
Opened 2017-05-17 16:25 UTC by awead

GA was not registering any file downloads because the configured dom id wasn't there. Also, the rake tasks that were caching this information were not executing.

Since download links can be in multiple places, we're opting for a class that can be applied to any link and will register that event in Google. The rake task wasn't executing because existing loading mechanisms weren't including all the correct code from the Legato gem.

2017-05-18 15:37 UTC, awead commented
@cam156 This fixes the capturing of the stats and the display, but the data gathering has some problems.
![stats](https://cloud.githubusercontent.com/assets/312085/26210627/3b78a546-3bbe-11e7-9147-d1b19355d78b.png)
I've note one issue here #856 but I'm sure there are other issues that we should capture in different tickets.

2017-05-18 16:05 UTC, carolyncole requested changes

2017-05-18 16:05 UTC, cam156 commented on app/views/curation_concerns/file_sets/_actions.html.erb
> +<div class="btn-group">
@awead can you add a comment here indicating that you are overriding the file to allow for download tracking?

2017-05-18 16:17 UTC, awead commented on app/views/curation_concerns/file_sets/_actions.html.erb
> +<div class="btn-group">
@cam156 it's on line 31, just above where the override is occurring.

2017-05-22 11:49 UTC, cam156 commented on app/views/curation_concerns/file_sets/_actions.html.erb
> +<div class="btn-group">
@awead It is easier to find it when it is at the top of the file.  The other files had the change at the top.  Why in this one did you only add it on the line?

2017-05-22 20:09 UTC, awead commented on app/views/curation_concerns/file_sets/_actions.html.erb
> +<div class="btn-group">
@cam156 for the other files, it made more sense to put it near the `if` block, which coincided with the top of the file. In the case of this file, there are many `if can?` blocks and it's not immediately evident that we added an additional one. I wanted the comment to go closest the one that we were adding so that it was more evident what changes were being made.

2017-05-23 13:12 UTC, cam156 commented on app/views/curation_concerns/file_sets/_actions.html.erb
> +<div class="btn-group">
@awead All I am asking for is an additional comment at the top of the file  to make it obvious the only reason this file was overridden was for download tracking.  Are you not willing to put that comment in?

2017-05-23 13:42 UTC, awead commented on app/views/curation_concerns/file_sets/_actions.html.erb
> +<div class="btn-group">
I've moved the comment.

2017-05-25 13:23 UTC, carolyncole approved these changes

2017-05-25 13:23 UTC, merged