Removes File Format Metadata for Works from Search Index View
psu-libraries/scholarsphere-3 pull request #982
Opened 2017-07-11 13:27 UTC by mtribone

Removes the file format field on the search view for works from the file configurator.

Removes file format from the common fields but adds it to the facet fields in the field configurator. Removes file format spec test from catalog controller, works controller, and field configurator because we are dealing with works not files.

2017-07-11 13:28 UTC, mtribone commented
![screen shot 2017-07-11 at 9 26 01 am](https://user-images.githubusercontent.com/4163828/28070530-38b5acaa-661b-11e7-95f7-22ad47eecd0d.png)

2017-07-11 15:18 UTC, carolyncole requested changes

2017-07-11 15:18 UTC, cam156 commented on spec/controllers/catalog_controller_spec.rb
> -      it "finds a file by format_label" do
@mtribone does this test fail?  Since you are still including the facet I would expect this test to pass

2017-07-11 16:29 UTC, mtribone commented on spec/controllers/catalog_controller_spec.rb
> -      it "finds a file by format_label" do
@cam156 Yes this test was failing until I removed it.

2017-07-11 16:47 UTC, mtribone commented on spec/controllers/catalog_controller_spec.rb
> -      it "finds a file by format_label" do
https://travis-ci.org/psu-stewardship/scholarsphere/jobs/252117848#L2250

2017-07-11 18:55 UTC, cam156 commented on spec/controllers/catalog_controller_spec.rb
> -      it "finds a file by format_label" do
@mtribone since you kept the facet that test "Should" pass.  There may need to be a tweak to the test now that the facet is not displayed the results.

2017-07-12 17:12 UTC, carolyncole approved these changes

2017-07-12 17:13 UTC, carolyncole requested changes

2017-07-12 17:13 UTC, cam156 commented on spec/controllers/my/works_controller_spec.rb
> -      it "finds a file by format_label" do
@mtribone I thought this was going to be back in.

2017-07-12 17:29 UTC, mtribone commented on spec/controllers/my/works_controller_spec.rb
> -      it "finds a file by format_label" do
@cam156 Oops. forgot about the works controller

2017-07-12 18:48 UTC, carolyncole approved these changes

2017-07-12 18:48 UTC, merged